namespace Skyline.DataMiner.DeveloperCommunityLibrary.YLE.Service.Configuration
{
	using Newtonsoft.Json;
	using Skyline.DataMiner.DeveloperCommunityLibrary.YLE.Integrations.Eurovision;
	using Skyline.DataMiner.DeveloperCommunityLibrary.YLE.Order;
	using Skyline.DataMiner.Utils.YLE.Integrations;
	using System;
	using System.Collections.Generic;

	public class ServiceConfiguration
	{
		/// <summary>
		/// The ID of the service.
		/// </summary>
		public Guid Id { get; set; }

		/// <summary>
		/// The name of the service.
		/// </summary>
		public string Name { get; set; }

		/// <summary>
		/// Start time configured for this service.
		/// </summary>
		public DateTime Start { get; set; }

		/// <summary>
		/// The preroll of the Service.
		/// This was added in case it doesn't match the predefined prerolls when booked very fast.
		/// </summary>
		public TimeSpan PreRoll { get; set; }

		/// <summary>
		/// End time configured for this service.
		/// </summary>
		public DateTime End { get; set; }

		/// <summary>
		/// The post roll of the Service.
		/// </summary>
		public TimeSpan PostRoll { get; set; }

		/// <summary>
		/// The previous generated service status.
		/// </summary>
		public string SavedStatus { get; set; }

		/// <summary>
		/// The service level (backup) for the service.
		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public BackupType? ServiceLevel { get; set; }

		/// <summary>
		/// Linked service Id, only applicable when active backup applies on the order this service belongs.
		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public Guid LinkedServiceId { get; set; }

		/// <summary>
		/// The function configurations for each function in this service.
		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public Dictionary<string, FunctionConfiguration> Functions { get; set; }

		/// <summary>
		/// The id of the service definition that is used for this service.
		/// </summary>
		public Guid ServiceDefinitionId { get; set; }

		/// <summary>
		/// Indicates which integration created this Service.
		/// If not specified this will be set to None.
		/// </summary>
		public IntegrationType IntegrationType { get; set; }

		public bool IntegrationIsMaster { get; set; }

		/// <summary>
		/// Indicates if this is an Eurovision service.
		/// </summary>
		public bool IsEurovisionService { get; set; }

		/// <summary>
		/// This is set to true from the HandleIntegrationUpdate script if the synopsis contains a value for the ioMuxName field.
		/// The ioMuxName field is used to define multiple multiplexed feeds in the signal.
		/// If this boolean is true, you will be able to edit the Service Selection profile parameter of the Satellite Reception in the LiveOrderForm.
		/// </summary>
		public bool IsEurovisionMultiFeedService { get; set; }

		/// <summary>
		/// Indicates if this service is a Shared Source or not.
		/// </summary>
		public bool IsGlobalEventLevelReception { get; set; }

		/// <summary>
		/// The id of the work order that has been requested from EBU.
		/// This can be used to map the incoming Eurovision synopsis to this service correctly.
		/// This is only applicable for EBU services that were requested through the LiveOrderForm.
		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public string EurovisionWorkOrderId { get; set; }

		/// <summary>
		/// The transmission number of the Eurovision synopsis in case of a Eurovision service.
		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public string EurovisionTransmissionNumber { get; set; }

		/// <summary>
		/// Serialized data of the Eurovision booking details as configured in the Customer UI.
		/// This is only applicable in case of an Eurovision service.
		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public EurovisionBookingDetails EurovisionBookingDetails { get; set; }

		/// <summary>
		/// This property is only used when the Service was generated by the EBU integration.
		/// In that case this property will contain the possible Receptions or Transmissions.
		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public List<ServiceConfiguration> EurovisionServiceConfigurations { get; set; }

		/// <summary>
		/// This property is only used when the Service is a Reception Service that was generated by the EBU integration.
		/// In that case this property will contain the id of the destination in the synopsis on which this service is based. 
		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public string EurovisionDestinationId { get; set; }

		/// <summary>
		/// This property is only used when the Service is a Reception or Transmission Service that was generated by the EBU integration.
		/// In that case this property will contain the id of the technical system in the synopsis on which this service is based. 
		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public string EurovisionTechnicalSystemId { get; set; }

		/// <summary>
		/// This property contains the ID of the EVS Recording Session if one was created.
		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public string EvsId { get; set; }

		/// <summary>
		/// If an issue has been reported manually via the UpdateService script and when the order is finished.
		/// The service will have the status Completed With Errors at the end.
		/// </summary>
		public bool HasAnIssueBeenreportedManually { get; set; } = false;

		/// <summary>
		/// Comments for this service.
		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public string Comments { get; set; }

		/// <summary>
		/// Contact Information Name.
		/// Only applicable for LiveU receptions.
		/// Will be saved in a custom property for LiveU receptions;
		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public string ContactInformationName { get; set; }

		/// <summary>
		/// Contact Information Telephone Number.
		/// Only applicable for LiveU receptions.
		/// Will be saved in a custom property for LiveU receptions;
		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public string ContactInformationTelephoneNumber { get; set; }

		/// <summary>
		/// Additional information LiveU device name.
		/// Only applicable for LiveU receptions or transmissions.
		/// Will be saved in a custom property for LiveU receptions or transmissions;
		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public string LiveUDeviceName { get; set; }

		/// <summary>
		/// Normal users will fill in this field when LiveU is selected
		/// News users will be able to fill in this field for every reception service.
		/// </summary>
		public string AudioReturnInfo { get; set; }

		/// <summary>
		/// Additional information Vidigo Stream Source Link.
		/// Only applicable for IP Receptions.
		/// Will be saved in a custom property.
		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public string VidigoStreamSourceLink { get; set; }

		/// <summary>
		/// Additional information about the desired source that should be selected whenever they want to book an order definitively.
		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public string AdditionalDescriptionUnknownSource { get; set; }

		/// <summary>
		/// Indicates if a source service is unknown.
		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public bool IsUnknownSourceService { get; set; }

		/// <summary>
		/// Indicates if the audio configuration is copied from source.
		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public bool IsAudioConfigurationCopiedFromSource { get; set; }

		/// <summary>
		/// Indicates if this service requires routing.
		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public bool RequiresRouting { get; set; }

		/// <summary>
		/// Indicates if routing config should be updated whenever applicable.
		/// </summary>
		public bool RoutingConfigurationUpdateRequired { get; set; }

		/// <summary>
		/// Flag indicating that the EVS automation should be triggered from the background if applicable.
		/// Usually used in certain cases where the foreground script would update an EVS Recording service in SRM.
		/// </summary>
		public bool MajorTimeslotChange { get; set; }

		/// <summary>
		/// The recording configuration with additional recording details that are not stored as profile parameters.
		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public RecordingConfiguration RecordingConfiguration { get; set; }

		public HashSet<int> SecurityViewIds { get; set; }

		/// <summary>
		/// Indicates if this service requires routing.
		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public HashSet<Guid> OrderReferences { get; set; }

		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public string NameOfServiceToTransmit { get; set; }

		public bool ChangedByUpdateServiceScript { get; set; } = false;

		/// <summary>
		/// Indication if this service is newly added to a running order and if it should start directly (start now) or at a later stage.
		/// </summary>
		public bool ShouldStartDirectly { get; set; }

		/// <summary>
		/// Paths of the synopsis files that were uploaded through the LiveOrderForm.
		/// These only apply to Satellite Rx services.
		/// </summary>
		[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
		public HashSet<string> SynopsisFiles { get; set; }


		public string Serialize()
		{
			return JsonConvert.SerializeObject(this, Formatting.None);
		}

		public static ServiceConfiguration Deserialize(string serviceConfigurationProfileParameterValue)
		{
			try
			{
				return JsonConvert.DeserializeObject<ServiceConfiguration>(serviceConfigurationProfileParameterValue);
			}
			catch (Exception)
			{
				return null;
			}
		}

		/// <summary>
		/// Used to create a deep copy of this ServiceConfiguration.
		/// </summary>
		/// <returns>Deep copy of the ServiceConfiguration.</returns>
		public ServiceConfiguration Copy()
		{
			string serializedConfig = Serialize();
			return Deserialize(serializedConfig);
		}
	}
}