// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Minor Code Smell", "S6602:\"Find\" method should be used instead of the \"FirstOrDefault\" extension", Justification = "<Pending>", Scope = "member", Target = "~M:Debug_2.Debug.ServiceDefinitions.FixMissingServiceDefinitionsDialog.MisingServiceDefinitionSection.GetEdges(System.Collections.Generic.IEnumerable{Skyline.DataMiner.Net.ServiceManager.Objects.Node})~System.Collections.Generic.IEnumerable{Skyline.DataMiner.Net.ServiceManager.Objects.Edge}")]
[assembly: SuppressMessage("Minor Code Smell", "S6602:\"Find\" method should be used instead of the \"FirstOrDefault\" extension", Justification = "<Pending>", Scope = "member", Target = "~M:Skyline.DataMiner.DeveloperCommunityLibrary.YLE.Integrations.SendPbsIntegrationNotificationDialog.NotificationSection_LoadButton_Pressed(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Minor Code Smell", "S6602:\"Find\" method should be used instead of the \"FirstOrDefault\" extension", Justification = "<Pending>", Scope = "member", Target = "~M:Skyline.DataMiner.DeveloperCommunityLibrary.YLE.UI.Debug.Integrations.AnalyzePlasmaRecordingsDialog.GetPgmRecording(Skyline.DataMiner.DeveloperCommunityLibrary.YLE.Order.Order)~Skyline.DataMiner.DeveloperCommunityLibrary.YLE.Service.Service")]
[assembly: SuppressMessage("Minor Code Smell", "S6602:\"Find\" method should be used instead of the \"FirstOrDefault\" extension", Justification = "<Pending>", Scope = "member", Target = "~M:Skyline.DataMiner.DeveloperCommunityLibrary.YLE.UI.Debug.Jobs.FindReservationsWithoutJobDialog.FixButton_Pressed(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Minor Code Smell", "S6602:\"Find\" method should be used instead of the \"FirstOrDefault\" extension", Justification = "<Pending>", Scope = "member", Target = "~M:Skyline.DataMiner.DeveloperCommunityLibrary.YLE.UI.Debug.Reservations.FindQuarantinedOrdersDialog.QuarantinedReservationSection.ResourceAssignmentSection.Initialize")]
[assembly: SuppressMessage("Minor Code Smell", "S6602:\"Find\" method should be used instead of the \"FirstOrDefault\" extension", Justification = "<Pending>", Scope = "member", Target = "~M:Skyline.DataMiner.DeveloperCommunityLibrary.YLE.UI.Debug.Reservations.FindQuarantinedOrdersDialog.QuarantinedReservationSection.ResourceAssignmentSection.UpdateResourceButton_Pressed(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Minor Code Smell", "S6602:\"Find\" method should be used instead of the \"FirstOrDefault\" extension", Justification = "<Pending>", Scope = "member", Target = "~P:Skyline.DataMiner.DeveloperCommunityLibrary.YLE.UI.Debug.Reservations.FindQuarantinedOrdersDialog.QuarantinedReservationSection.ResourceAssignmentSection.FunctionSection.SelectedResource")]
[assembly: SuppressMessage("Minor Code Smell", "S6608:Prefer indexing instead of \"Enumerable\" methods on types implementing \"IList\"", Justification = "<Pending>", Scope = "member", Target = "~M:Skyline.DataMiner.DeveloperCommunityLibrary.YLE.UI.Debug.Resources.FixResourceConfigurationDialog.UpdateResourcesButton_Pressed(System.Object,System.EventArgs)")]
