<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <OutputType>Library</OutputType>
    <AssemblyName>LibraryD</AssemblyName>
    <PackageId>Test.LibraryD</PackageId>
    <AssemblyVersion>4.4.0.0</AssemblyVersion>

    <IsPackable>false</IsPackable>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CsvHelper" Version="30.0.1" />
  </ItemGroup>

</Project>