namespace Skyline.DataMiner.DeveloperCommunityLibrary.YLE.Integrations.Ceiton
{
	using System;
	using System.Linq;
	using Skyline.DataMiner.DeveloperCommunityLibrary.YLE.Event;
	using Skyline.DataMiner.DeveloperCommunityLibrary.YLE.Integrations;
	using Skyline.DataMiner.DeveloperCommunityLibrary.YLE.Order.OrderManagerElement;
	using Skyline.DataMiner.DeveloperCommunityLibrary.YLE.Utilities;
	using Skyline.DataMiner.Utils.YLE.Integrations;
	using Skyline.DataMiner.Utils.YLE.Integrations.Ceiton;

	/// <summary>
	/// Ceiton Integration class.
	/// </summary>
	public class CeitonIntegration : Integration
	{
		public CeitonIntegration(Helpers helpers, OrderManagerElement orderManagerElement) : base(helpers, orderManagerElement)
		{

		}

		public override IntegrationType IntegrationType => IntegrationType.Ceiton;

		protected override string IntegrationText => "Automatically generated by Ceiton integration.";

		public override void HandleUpdate(string id, string integrationData)
		{
			Project project = ParseProject(integrationData);
			if (project != null)
			{
				AddOrUpdateProject(project);
			}
			else
			{
				DeleteProject(id);
			}
		}

		private Project ParseProject(string serializedProject)
        {
			try
            {
				return Project.Deserialize(serializedProject);
			}
			catch (Exception e)
            {
				Log(nameof(ParseProject), $"Unable to parse project: {e}");
				return null;
            }
        }

		private Event GenerateCeitonEvent(Project project, Event eventInfo)
		{
			if (eventInfo == null)
			{
				// Add new Event
				eventInfo = GenerateNewCeitonEvent(project.Name, project.Number, project.Products.Select(p => p.Number), (DateTime)project.Start, (DateTime)project.End);
			}
			else
			{
				// Edit - Update product numbers and event name
				eventInfo.Name = String.Format("{0}[{1}]", project.Name, project.Number);
				eventInfo.ProductNumbers = project.Products.Select(p => p.Number).Distinct().ToList();
				eventInfo.IntegrationType = IntegrationType.Ceiton;
			}

			UpdateEventContractAndRights(eventInfo);

			return eventInfo;
		}

		private void AddOrUpdateProject(Project project)
		{
			// Check if the project is eligible for Event creation
			var eligibility = project.IsEligibleForEventCreation();
			if (!eligibility.IsEligible)
			{
				SendResponseToOrderManagerElement(project.Number, UpdateStatus.OK, $"AddOrUpdateProject|No action required|{eligibility.Reason}");
				return;
			}

			var existingEvent = helpers.EventManager.GetEvent(project.Number);
			if (existingEvent == null)
            {
				// New event
				if (project.Start == null || project.End == null)
                {
					SendResponseToOrderManagerElement(project.Number, UpdateStatus.OK, $"AddOrUpdateProject|No action required|Unable to create new Ceiton event because timing is not valid");
					return;
				}

				if (project.End < DateTime.Now)
                {
					SendResponseToOrderManagerElement(project.Number, UpdateStatus.OK, $"AddOrUpdateProject|No action required|Unable to create new Ceiton event because end time is in the past");
					return;
				}
			}
			else
            {
				// Existing event
				RetrieveLock(existingEvent);
			}

			Event eventInfo = GenerateCeitonEvent(project, existingEvent);

			try
			{
				if (helpers.EventManager.AddOrUpdateEvent(eventInfo))
				{
					SendResponseToOrderManagerElement(project.Number, UpdateStatus.OK, "AddOrUpdateProject|Action succeeded|Adding or updating event succeeded", null, eventInfo.Id);
				}
				else
				{
					SendResponseToOrderManagerElement(project.Number, UpdateStatus.Failed, "AddOrUpdateProject|Action failed|Adding or updating event failed");
				}
			}
			catch (Exception e)
			{
				SendResponseToOrderManagerElement(project.Number, UpdateStatus.Failed, $"AddOrUpdateProject|Action failed|Adding or updating event failed: {e}");
			}
		}

		private void DeleteProject(string id)
		{
			try
			{
				var eventInfo = helpers.EventManager.GetEvent(id);
				if (eventInfo is null)
				{
					SendResponseToOrderManagerElement(id, UpdateStatus.OK, "DeleteProject|No action required|Event does not exist");
				}
				else if (helpers.EventManager.HasOrders(eventInfo.Id))
                {
					SendResponseToOrderManagerElement(id, UpdateStatus.OK, "DeleteProject|No action required|Event was not removed as it contains some orders");
				}
				else if (helpers.EventManager.DeleteEvent(eventInfo.Id))
				{
					SendResponseToOrderManagerElement(id, UpdateStatus.OK, "DeleteProject|Action succeeded|Removing event succeeded");
				}
				else
				{
					SendResponseToOrderManagerElement(id, UpdateStatus.Failed, "DeleteProject|Action failed|Removing event failed");
				}
			}
			catch (Exception e)
			{
				SendResponseToOrderManagerElement(id, UpdateStatus.Failed, $"DeleteProject|Action failed|Removing event failed: {e}");
			}
		}
	}
}