namespace Skyline.DataMiner.DeveloperCommunityLibrary.YLE.UI.Service
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
	using Skyline.DataMiner.DeveloperCommunityLibrary.YLE.Metrics;
	using Skyline.DataMiner.DeveloperCommunityLibrary.YLE.Order;
	using Skyline.DataMiner.DeveloperCommunityLibrary.YLE.Service;
	using Skyline.DataMiner.DeveloperCommunityLibrary.YLE.ServiceDefinition;
	using Skyline.DataMiner.DeveloperCommunityLibrary.YLE.Utilities;

	/// <summary>
	/// Contains the service sections that are displayed in an order section
	/// </summary>
	public class ServiceSectionCollection
	{
		public ServiceSection SourceServiceSection { get; set; }

		public ServiceSection BackupSourceServiceSection { get; set; }

		public Dictionary<Guid, ServiceSection> CachedSourceServiceSections { get; private set; } = new Dictionary<Guid, ServiceSection>();

		public Dictionary<Guid, ServiceSection> CachedBackupSourceServiceSections { get; private set; } = new Dictionary<Guid, ServiceSection>();

		public IReadOnlyDictionary<VirtualPlatformType, List<LinkedServiceSectionCollection>> EndpointSections { get; private set; } = new Dictionary<VirtualPlatformType, List<LinkedServiceSectionCollection>>
		{
			{ VirtualPlatformType.Destination, new List<LinkedServiceSectionCollection>() },
			{ VirtualPlatformType.Recording, new List<LinkedServiceSectionCollection>() },
			{ VirtualPlatformType.Transmission, new List<LinkedServiceSectionCollection>() },
			{ VirtualPlatformType.VizremFarm, new List<LinkedServiceSectionCollection>() },
			{ VirtualPlatformType.VizremStudio, new List<LinkedServiceSectionCollection>() },
		};

		/// <summary>
		/// Saves sections for sub services under the ID of the related endpoint service.
		/// If there is no related endpoint service, then the key is empty Guid.
		/// </summary>
		public Dictionary<Guid, List<ServiceSelectionSection>> SubSections { get; private set; } = new Dictionary<Guid, List<ServiceSelectionSection>>();

		public IReadOnlyDictionary<VirtualPlatformType, List<LinkedServiceSectionCollection>> BackupEndpointSections { get; private set; } = new Dictionary<VirtualPlatformType, List<LinkedServiceSectionCollection>>
		{
			{ VirtualPlatformType.Destination, new List<LinkedServiceSectionCollection>() },
			{ VirtualPlatformType.Recording, new List<LinkedServiceSectionCollection>() },
			{ VirtualPlatformType.Transmission, new List<LinkedServiceSectionCollection>() },
		};

		public List<ServiceSelectionSection> RebuildSubSectionsDictionary(Helpers helpers, Order order)
		{
			using (MetricLogger.StartNew(helpers, nameof(ServiceSectionCollection), nameof(RebuildSubSectionsDictionary)))
			{
				var newlyGeneratedSections = new List<ServiceSelectionSection>();

				var allExistingSubServiceSections = SubSections.Values.SelectMany(x => x).ToList();

				SubSections.Clear();

				var recordingsAfterDestinations = order.AllServices.Where(s => s.IsRecordingAfterDestination(order)).ToList();
				var autoGeneratedServices = order.AllServices.Where(s => s.IsAutogenerated);

				var subServices = recordingsAfterDestinations.Union(autoGeneratedServices);

				foreach (var subService in subServices)
				{
					newlyGeneratedSections.AddRange(AddOrUpdateSubServiceSection(helpers, order, subService, allExistingSubServiceSections));
				}

				return newlyGeneratedSections;
			}
		}

		private List<ServiceSelectionSection> AddOrUpdateSubServiceSection(Helpers helpers, Order order, Service subService, List<ServiceSelectionSection> allExistingSubServiceSections)
		{
			List<ServiceSelectionSection> newlyGeneratedSections = new List<ServiceSelectionSection>();
			var existingSubServiceSections = allExistingSubServiceSections.Where(ss => ss.Service.Equals(subService)).ToList();
			if (!existingSubServiceSections.Any())
			{
				helpers.Log(nameof(ServiceSectionCollection), nameof(RebuildSubSectionsDictionary), $"No existing sections for sub service {subService.Name}");
				return newlyGeneratedSections; // skip when the section does not exist yet, it should be coming later
			}

			helpers.Log(nameof(ServiceSectionCollection), nameof(RebuildSubSectionsDictionary), $"Found existing sections for sub service {subService.Name}: {string.Join(", ", existingSubServiceSections.Select(x => x.ToString()))}");

			List<Service> relatedEndpoints;
			if (subService.IsAutogenerated)
			{
				var endpointDescendants = subService.Descendants.Where(s => s.Definition.IsEndPointService && !s.IsRecordingAfterDestination(order)).ToList();
				relatedEndpoints = endpointDescendants;
			}
			else
			{
				var destinationParent = order.AllServices.Single(s => s.Children.Contains(subService));
				relatedEndpoints = destinationParent.Yield().ToList();
			}

			helpers.Log(nameof(ServiceSectionCollection), nameof(RebuildSubSectionsDictionary), $"Related endpoints for sub service {subService.Name} are '{string.Join(", ", relatedEndpoints.Select(s => s.Name))}'");

			if (relatedEndpoints.Any())
			{
				int amountOfMissingSubServiceSections = relatedEndpoints.Count - existingSubServiceSections.Count;
				if (amountOfMissingSubServiceSections > 0)
				{
					for (int i = 0; i < amountOfMissingSubServiceSections; i++)
					{
						var newSubServiceSection = (ServiceSelectionSection)existingSubServiceSections.First().Clone();
						existingSubServiceSections.Add(newSubServiceSection);

						helpers.Log(nameof(ServiceSectionCollection), nameof(RebuildSubSectionsDictionary), $"Created new section {newSubServiceSection}");

						newlyGeneratedSections.Add(newSubServiceSection);
					}
				}

				for (int i = 0; i < relatedEndpoints.Count; i++)
				{
					AddSubServiceSection(existingSubServiceSections[i], relatedEndpoints[i].Id);
				}
			}
			else
			{
				AddSubServiceSection(existingSubServiceSections.First());
			}

			return newlyGeneratedSections;
		}

		public bool ChildServiceIsAlreadyAdded(Service childService)
		{
			if (childService.IsAutogenerated)
			{
				return SubSections.Values.SelectMany(x => x).Any(x => x.Service.Equals(childService));
			}
			else if (childService.BackupType == BackupType.None)
			{
				return EndpointSections[childService.Definition.VirtualPlatformServiceType].Any(x => x.Contains(childService.Id));
			}
			else
			{
				return BackupEndpointSections[childService.Definition.VirtualPlatformServiceType].Any(x => x.Contains(childService.Id));
			}
		}

		public void AddSubServiceSection(ServiceSelectionSection section, Guid? endpointServiceId = null)
		{
			var validEndpointServiceId = endpointServiceId.HasValue ? endpointServiceId.Value : Guid.Empty;

			if (!SubSections.TryGetValue(validEndpointServiceId, out var subServiceSectionsForEndpoint))
			{
				subServiceSectionsForEndpoint = new List<ServiceSelectionSection>();
				SubSections[validEndpointServiceId] = subServiceSectionsForEndpoint;
			}

			subServiceSectionsForEndpoint.Add(section);
		}

		public void AddCollection(LinkedServiceSectionCollection collection)
		{
			var addedService = collection.DisplayedSection.Service;

			if (addedService.BackupType == BackupType.None)
			{
				EndpointSections[addedService.Definition.VirtualPlatformServiceType].Add(collection);
			}
			else
			{
				BackupEndpointSections[addedService.Definition.VirtualPlatformServiceType].Add(collection);
			}
		}

		public LinkedServiceSectionCollection GetLinkedServiceSectionCollectionForService(Service service)
		{
			if (service.BackupType == BackupType.None && EndpointSections.TryGetValue(service.Definition.VirtualPlatformServiceType, out var mainSourceChildServiceSectionCollection))
			{
				return mainSourceChildServiceSectionCollection.SingleOrDefault(col => col.Contains(service.Id));
			}
			else if (BackupEndpointSections.TryGetValue(service.Definition.VirtualPlatformServiceType, out var backupSourceChildServiceSectionCollection))
			{
				return backupSourceChildServiceSectionCollection.SingleOrDefault(col => col.Contains(service.Id));
			}
			else
			{
				return null;
			}
		}

		public void RemoveCollectionContainingService(Service service)
		{
			if (service.IsAutogenerated)
			{
				foreach (var subServiceSelectionSections in SubSections.Values)
				{
					subServiceSelectionSections.RemoveAll(x => x.Service.Equals(service));
				}
			}
			else if (service.BackupType == BackupType.None)
			{
				if (EndpointSections.TryGetValue(service.Definition.VirtualPlatformServiceType, out var mainSourceChildServiceSectionCollection))
				{
					mainSourceChildServiceSectionCollection.RemoveAll(x => x.Contains(service.Id));
				}
			}
			else
			{
				if (BackupEndpointSections.TryGetValue(service.Definition.VirtualPlatformServiceType, out var backupSourceChildServiceSectionCollection))
				{
					backupSourceChildServiceSectionCollection.RemoveAll(x => x.Contains(service.Id));
				}
			}
		}

		public IEnumerable<ServiceSelectionSection> GetSubServiceSections(Guid endpointServiceId)
		{
			return SubSections.TryGetValue(endpointServiceId, out var subServiceSections) ? subServiceSections : new List<ServiceSelectionSection>();
		}
	}
}
