<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <OutputType>Library</OutputType>
    <AssemblyName>Diamond.LibraryD</AssemblyName>
    <PackageId>Diamond.LibraryD</PackageId>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
</Project>