namespace Skyline.DataMiner.DeveloperCommunityLibrary.YLE.Integrations.PebbleBeach
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using Skyline.DataMiner.DeveloperCommunityLibrary.YLE.Integrations;
	using Skyline.DataMiner.DeveloperCommunityLibrary.YLE.Order;
	using Skyline.DataMiner.DeveloperCommunityLibrary.YLE.Order.OrderManagerElement;
	using Skyline.DataMiner.DeveloperCommunityLibrary.YLE.Tasks;
	using Skyline.DataMiner.DeveloperCommunityLibrary.YLE.Tasks.OrderTasks;
	using Skyline.DataMiner.DeveloperCommunityLibrary.YLE.Utilities;
	using Skyline.DataMiner.Utils.YLE.Integrations;
	using Skyline.DataMiner.Utils.YLE.Integrations.PebbleBeach;
	using OrderStatus = Skyline.DataMiner.DeveloperCommunityLibrary.YLE.Order.Status;
	using TaskStatus = Skyline.DataMiner.DeveloperCommunityLibrary.YLE.Tasks.Status;

	/// <summary>
	/// Pebble Beach Integration class.
	/// </summary>
	public class PebbleBeachIntegration : Integration
	{
		public PebbleBeachIntegration(Helpers helpers, OrderManagerElement orderManagerElement) : base(helpers, orderManagerElement)
		{
		}

		public override IntegrationType IntegrationType => IntegrationType.PebbleBeach;

		protected override string IntegrationText => "Automatically generated by Pebble Beach integration";

		public override void HandleUpdate(string id, string integrationData)
		{
			if (!TryParsePbsEvent(integrationData, out PbsEvent pbsEvent))
            {
				Log(nameof(HandleUpdate), $"Unable to parse Pebble Beach Event -> no action performed");
				SendResponseToOrderManagerElement(id, UpdateStatus.Failed, "HandleUpdate|No action performed|Unable to parse Pebble Beach event");
				return;
			}

			if (pbsEvent == null)
			{
				SendResponseToOrderManagerElement(id, UpdateStatus.Removed, $"HandleUpdate|No action executed|Pebble Beach Event with ID {id} was removed from the playlist");
				return;
			}

			var plasmaOrder = helpers.OrderManager.GetPlasmaOrder("dummy", pbsEvent.PlasmaId);
            
			if (plasmaOrder == null)
			{
				// No linked existing Plasma Order -> nothing to do
				SendResponseToOrderManagerElement(id, UpdateStatus.OK, $"HandleUpdate|No action executed|No linked Plasma order found with Plasma ID {pbsEvent.PlasmaId}");
				return;
			}

			if (DateTime.Now.AddMinutes(30) < pbsEvent.EstimatedStartTime)
			{
				// Pebble Beach Integration should only handle updates 30 min before the order is going live
				SendResponseToOrderManagerElement(id, UpdateStatus.OK, $"HandleUpdate|No action executed|Update ignored as it is before the 30 minutes to live timeframe (Estimated start time: {pbsEvent.EstimatedStartTime})");
				return;
			}

			RetrieveLock(plasmaOrder);

			if (!UpdatePlasmaOrder(pbsEvent, plasmaOrder))
			{
				SendResponseToOrderManagerElement(id, UpdateStatus.Failed, "HandleUpdate|Action failed|Adding or updating order failed", plasmaOrder.Id, plasmaOrder.Event.Id);
				return;
			}

			SendResponseToOrderManagerElement(id, UpdateStatus.OK, "HandleUpdate|Action succeeded|Adding or updating order succeeded", plasmaOrder.Id, plasmaOrder.Event.Id);
		}

		private bool TryParsePbsEvent(string serializedPbsEvent, out PbsEvent pbsEvent)
		{
			pbsEvent = null;
			try
			{
				pbsEvent = PbsEvent.Deserialize(serializedPbsEvent);
			}
			catch (Exception e)
			{
				Log(nameof(TryParsePbsEvent), $"Unable to parse Pebble Beach event: {e}");
				return false;
			}

			return true;
		}

		private bool UpdatePlasmaOrder(PbsEvent pbsEvent, Order order)
		{
			try
			{
				helpers.AddOrderReferencesForLogging(order.Id);

				var tasks = GetUpdateTasks(pbsEvent, order);

				foreach (var task in tasks.Where(x => x.Status == TaskStatus.Fail))
				{
					helpers.Log(nameof(PebbleBeachIntegration), nameof(UpdatePlasmaOrder), "Failed to execute task: " + task.Description);
				}

				if (tasks.Any(x => x.Status == TaskStatus.Fail && x.IsBlocking))
				{
					// Some Order creation tasks failed
					if (!RollBackTasks(tasks))
					{
						helpers.Log(nameof(PebbleBeachIntegration), nameof(UpdatePlasmaOrder), "Rollback failed");
					}

					return false;
				}
			}
			catch (Exception e)
			{
				helpers.Log(nameof(PebbleBeachIntegration), nameof(UpdatePlasmaOrder), "Something went wrong: " + e);
				return false;
			}

			return true;
		}

		/// <summary>
		/// Rolls back the tasks that failed when adding or updating an order in SRM.
		/// </summary>
		/// <param name="tasks">List of tasks that were executed when adding or updating an Order in SRM.</param>
		/// <returns>True if the rollback was successful, else false.</returns>
		private static bool RollBackTasks(IEnumerable<Task> tasks)
		{
			List<Task> rollbackTasks = tasks.Where(t => t.Status == TaskStatus.Ok).Select(t => t.CreateRollbackTask()).Where(t => t != null).Reverse().ToList();

			foreach (Task rollbackTask in rollbackTasks)
			{
				if (!rollbackTask.Execute()) return false;
			}

			return true;
		}

		private IEnumerable<Task> GetUpdateTasks(PbsEvent pbsEvent, Order order)
		{
			if (pbsEvent.ActualEndTime.HasValue)
			{
				if (order.ShouldBeRunning)
				{
					return StopRunningOrder(order);
				}
			}
			else
			{
				if (pbsEvent.ActualStartTime.HasValue && order.Status != OrderStatus.Running)
				{
					return StartOrderNow(order);
				}
				else
				{
					return UpdateOrderTiming(pbsEvent, order);
				}
			}

			return new List<Task>();
		}

		private List<Task> StopRunningOrder(Order order)
		{
			List<Task> tasks = new List<Task>();

			helpers.Log(nameof(PebbleBeachIntegration), nameof(StopRunningOrder), "Stopping Pebble Beach Order");

			// Stop order
			var stopOrderTask = new StopOrderTask(helpers, order);
			stopOrderTask.Execute();
			tasks.Add(stopOrderTask);

			order.IntegrationType = IntegrationType.PebbleBeach;
			order.LastUpdatedBy = "Pebble Beach";
			order.Comments = "Automatically updated by Pebble Beach Integration";

			// Update custom properties
			var updateCustomPropertiesTask = new UpdateCustomPropertiesTask(helpers, order, order);
			updateCustomPropertiesTask.Execute();
			tasks.Add(updateCustomPropertiesTask);

			return tasks;
		}

		private List<Task> StartOrderNow(Order order)
		{
			List<Task> tasks = new List<Task>();

			helpers.Log(nameof(PebbleBeachIntegration), nameof(StartOrderNow), "Starting Pebble Beach Order");

			// Start order now
			var startOrderTask = new StartOrderTask(helpers, order);
			startOrderTask.Execute();
			tasks.Add(startOrderTask);

			order.IntegrationType = IntegrationType.PebbleBeach;
			order.LastUpdatedBy = "Pebble Beach";
			order.Comments = "Automatically updated by Pebble Beach Integration";
			order.SetMcrLateChangeRequired(helpers, userIsMcr: false);

			// Update custom properties
			var updateCustomPropertiesTask = new UpdateCustomPropertiesTask(helpers, order, order);
			updateCustomPropertiesTask.Execute();
			tasks.Add(updateCustomPropertiesTask);

			return tasks;
		}

		private List<Task> UpdateOrderTiming(PbsEvent pbsEvent, Order order)
		{
			List<Task> tasks = new List<Task>();

			helpers.Log(nameof(PebbleBeachIntegration), nameof(UpdateOrderTiming), $"Updating start time from {order.Start} to {pbsEvent.EstimatedStartTime}, updating end time from {order.End} to {pbsEvent.EstimatedEndTime}");

			order.AcceptChanges();
			var allServices = order.AllServices;

			order.IntegrationType = IntegrationType.PebbleBeach;
			order.LastUpdatedBy = "Pebble Beach";
			order.Comments = "Automatically updated by Pebble Beach Integration";
			order.SetMcrLateChangeRequired(helpers, userIsMcr: false);

			order.Start = pbsEvent.EstimatedStartTime;
			order.End = pbsEvent.EstimatedEndTime;

			foreach (var service in order.AllServices.Where(x => !x.IsSharedSource))
			{
				service.Start = pbsEvent.EstimatedStartTime;
				service.End = pbsEvent.EstimatedEndTime;
			}

			var updateResult = order.AddOrUpdate(helpers, false);
			tasks.AddRange(updateResult.Tasks);

			return tasks;
		}
	}
}
