<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <OutputType>Library</OutputType>
    <AssemblyName>Diamond.LibraryC</AssemblyName>
    <PackageId>Diamond.LibraryC</PackageId>
    <AssemblyVersion>3.0.0.0</AssemblyVersion>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LibraryD\LibraryD.csproj" />
  </ItemGroup>
</Project>