name: DataMiner CICD NuGet Solution

on:
  push:
    branches:
      - '**'
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+-**"

  workflow_dispatch:

jobs:

  CICD:
    uses: SkylineCommunications/_ReusableWorkflows/.github/workflows/Master Workflow.yml@MasterWorkflow
    with:
      sonarcloud-project-name: SkylineCommunications_Skyline.DataMiner.CICD.Packages
      solution-filter-name: Skyline.DataMiner.CICD.Packages.sln
      runs-on: windows-latest
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGETAPIKEY }}
